### PR TITLE
JAVA-1518: Expose metrics

### PR DESCRIPTION
**Pull request by olim7t**
Design goals:
* metrics can be enabled or disabled individually.
* disabled metrics are transparent for the driver code (no `if (metricEnabled)` tests) and have minimal runtime overhead.
* metrics can be node-level or session-level.
* the driver simply exposes a `MetricRegistry` and makes no assumption about how they will be exported; JMX is trivial (as shown below), so I don't think we need to build it in. In the same vein, individual metric objects are not exposed directly through the API (I doubt many people used that in 3.x, 99% of the time they will be exported to a monitoring tool with a reporter).

Basic manual test:
```java
try (CqlSession session = CqlSession.builder().build();
    JmxReporter reporter =
        JmxReporter.forRegistry(session.getMetricRegistry())
            .inDomain("com.datastax.oss.driver")
            .build()) {

  reporter.start();
  for (int i = 0; i < 1000; i++) {
    session.execute("select release_version from system.local");
  }
  TimeUnit.MINUTES.sleep(10);
}
```
Then connect to the process with jvisualvm or jconsole to observe the JMX MBeans.

The first commit is a PoC with a minimal set of metrics. TODO:
- [x] add remaining metrics (figure out what we want per node vs. per session, if we allow redundancy...)
- [x] switch `Timer` to an HDRHistogram-based implementation (either 3rd-party or custom).
- [x] tests

### CODE REVIEW

File: core/pom.xml [hunk 1]
```diff
@@ -75,6 +77,15 @@
       <groupId>org.slf4j</groupId>
       <artifactId>slf4j-api</artifactId>
     </dependency>
+    <dependency>
+      <groupId>io.dropwizard.metrics</groupId>
+      <artifactId>metrics-core</artifactId>
+    </dependency>
+    <dependency>
```
Comment (adutra) [inline core/pom.xml:84]: A few remarks about JMX:

1) `metrics-jmx` does not seem used at all, not even in tests. Is this intentional? 
2) More broadly speaking, are you leaning towards the idea of not providing JMX support inside the driver and leave that for users?
3) You seem to be creating hierarchical metric names such as `s0.nodes.127_0_0_1_9042.retries`. If you provide out-of-the-box JMX support, the nice thing is that you could customize your MBeans by creating hierarchical beans that reflect your internal hierarchy of metrics.

File: core/src/main/java/com/datastax/oss/driver/api/core/metrics/CoreNodeMetric.java [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+public enum CoreNodeMetric implements NodeMetric {
+
+  /**
+   * The number of connections open to this node for regular requests (exposed as a {@link Gauge
+   * Gauge&lt;Integer&gt;}.
+   *
+   * <p>This does not include the control connection (which uses at most one extra connection to a
+   * random node in the cluster).
+   */
+  pooled_connection_count,
```
Comment (adutra) [inline core/src/main/java/com/datastax/oss/driver/api/core/metrics/CoreNodeMetric.java]: Can't we stick to standards and use upper-case enum constant names?

File: core/src/main/java/com/datastax/oss/driver/internal/core/metadata/DefaultNode.java [hunk 3]
```diff
@@ -50,8 +53,11 @@
 
   volatile NodeDistance distance;
 
-  public DefaultNode(InetSocketAddress connectAddress) {
+  public DefaultNode(InetSocketAddress connectAddress, InternalDriverContext context) {
     this.connectAddress = connectAddress;
+    // We leak a reference to a partially constructed object (this), but in practice this won't be a
+    // problem because the node updater only needs the connect address to initialize.
+    this.metricUpdater = context.metricUpdaterFactory().newNodeUpdater(this);
```
Comment (adutra) [inline core/src/main/java/com/datastax/oss/driver/internal/core/metadata/DefaultNode.java]: it seems a little worse than that, I see that the constructor of `DefaultNodeUpdater` also tries to do the following:
```
ChannelPool pool = context.poolManager().getPools().get(node);
```

File: core/src/main/java/com/datastax/oss/driver/internal/core/metrics/DefaultNodeMetricUpdater.java [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+                ChannelPool pool = context.poolManager().getPools().get(node);
+                return (pool == null) ? 0 : pool.getAvailableIds();
+              });
+    }
+  }
+
+  @Override
+  public void markMeter(NodeMetric metric) {
+    if (enabledMetrics.contains(metric)) {
+      metricRegistry.meter(metricNamePrefix + metric.name()).mark();
```
Comment (adutra) [inline core/src/main/java/com/datastax/oss/driver/internal/core/metrics/DefaultNodeMetricUpdater.java]: Hmm what if the metric in question is not a `Meter`? Would you create a new method here? I guess what i'm getting at is:  maybe `NodeMetric` should somehow convey the metric type, and not only the metric name, so that we can update the right metric without risking a mistake here? It could maybe even update itself, stg like:
```
NodeMetric metric = ...
metric.update(context); // get the registry and the session name from here and update the relevant metric
```
... in which case, the logic from `NodeMetricUpdater` could be merged into `NodeMetric`.

File: core/src/test/resources/logback-test.xml [hunk 5]
```diff
@@ -25,4 +25,5 @@
         <appender-ref ref="STDOUT"/>
     </root>
     <logger name="com.datastax.oss.driver" level= "${driverLevel:-WARN}"/>
+    <logger name="Tmp" level= "DEBUG"/>
```
Comment (adutra) [inline core/src/test/resources/logback-test.xml]: What is this logger for?

File: pom.xml [hunk 6]
```diff
@@ -43,6 +43,7 @@
     <format.validateOnly>true</format.validateOnly>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
+    <metrics.version>4.0.0</metrics.version>
```
Comment (adutra) [inline pom.xml]: 4.0.2 is the latest version.

**Review by adutra — CHANGES_REQUESTED** [review]

File: core/pom.xml (hunk 1 above)
Comment (olim7t) [reply core/pom.xml:84]: 1. True, I added it to write my manual test class, but it's not used elsewhere and might not even be used in future tests. Removing it.
2. Yes. I don't see any need to have it out of the box because a) Adding a JMX reporter is trivial (two lines of code) and b) it's not recommended in production so users are likely to use something else.
3. I don't understand, as far as I can tell the JMX reporter does already create a hierarchy based on the dot separators in the metric names. When I look up the MBeans in jvisualvm, `retries` is a child of `127_0_0_1_9042`, etc.

File: core/src/main/java/com/datastax/oss/driver/internal/core/metadata/DefaultNode.java (hunk 3 above)
Comment (olim7t) [reply core/src/main/java/com/datastax/oss/driver/internal/core/metadata/DefaultNode.java]: That's actually done in a lambda that isn't invoked until you read the corresponding gauge (and anyway the hashcode of `DefaultNode` also happens to only use the connect address).

File: pom.xml (hunk 6 above)
Comment (olim7t) [reply pom.xml]: :+1: Fixed

File: core/src/test/resources/logback-test.xml (hunk 5 above)
Comment (olim7t) [reply core/src/test/resources/logback-test.xml]: Hehe, that's an accidental commit, fixing.

File: core/src/main/java/com/datastax/oss/driver/internal/core/metrics/DefaultNodeMetricUpdater.java (hunk 4 above)
Comment (olim7t) [reply core/src/main/java/com/datastax/oss/driver/internal/core/metrics/DefaultNodeMetricUpdater.java]: Yes, there will be a method for each metric type: `markMeter`,  `updateTimer`, `incrementCounter`, etc.
The caller is expected to know what type of metric each enum constant corresponds to. A mistake is very unlikely because it's all driver code, and the same person will add a metric and add the code to update it. And if a mistake does happen the error should be pretty obvious.

The problem with something like `NodeMetric#update` is that `NodeMetric` couldn't be an enum anymore (because it would need a reference to the `Meter`, which is created at runtime, and also because there could be multiple instances for separate sessions). Then the list of metric names wouldn't be known statically, we'd probably need a `NodeMetricRegistry` in order to validate the configuration, etc. The (very low) risk of a mistake does not justify all that complexity IMO.

File: core/src/main/java/com/datastax/oss/driver/api/core/metrics/CoreNodeMetric.java (hunk 2 above)
Comment (olim7t) [reply core/src/main/java/com/datastax/oss/driver/api/core/metrics/CoreNodeMetric.java]: I deliberately broke the convention because metric-land seems to favor lower case (from what I saw by looking at a few monitoring tools), and I find it nice to have a direct correspondence between the metric name and constant name.

If we want to respect the convention at all cost I could add a `getMetricName` that returns the lower-case version, but then it's a bit of a pity to have to explain that sometimes it's upper-case and sometimes lower.

File: core/src/main/java/com/datastax/oss/driver/api/core/config/CoreDriverOption.java [hunk 7]
```diff
@@ -108,6 +108,9 @@
   TIMESTAMP_GENERATOR_DRIFT_WARNING_INTERVAL(
       "request.timestamp-generator.drift-warning.interval", false),
 
+  METRICS_SESSION_ENABLED("metrics.session.enabled", false),
```
Comment (tolbertam) [inline core/src/main/java/com/datastax/oss/driver/api/core/config/CoreDriverOption.java:112]: 💯 for separating session and node level metrics!

File: core/src/main/java/com/datastax/oss/driver/api/core/metrics/NodeMetric.java [hunk 8]
```diff
@@ -0,0 +1,46 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package com.datastax.oss.driver.api.core.metrics;
+
+import com.datastax.oss.driver.api.core.session.Session;
+import java.net.InetAddress;
+
+/**
```
Comment (tolbertam) [inline core/src/main/java/com/datastax/oss/driver/api/core/metrics/NodeMetric.java:21]: Excellent docs 👍

File: core/src/main/resources/reference.conf [hunk 9]
```diff
@@ -550,6 +550,21 @@ datastax-java-driver {
     token-map.enabled = true
   }
 
+  metrics {
```
Comment (tolbertam) [inline core/src/main/resources/reference.conf:569]: I think it's cool that you can enable/disable specific metrics.  If you have a metrics db (graphite, influx, etc.) that a lot of clients are feeding into, it's pretty easy to overwhelm it, so to be able to be selective about what you record is nice.

**Review by tolbertam — COMMENTED** [review]
Looks great so far 👍

File: core/pom.xml (hunk 1 above)
Comment (adutra) [reply core/pom.xml:84]: > as far as I can tell the JMX reporter does already create a hierarchy based on the dot separators in the metric names

Was this available since metrics 3? I didn't know. OK then.

File: core/src/main/java/com/datastax/oss/driver/internal/core/metrics/DefaultNodeMetricUpdater.java (hunk 4 above)
Comment (adutra) [reply core/src/main/java/com/datastax/oss/driver/internal/core/metrics/DefaultNodeMetricUpdater.java]: Sounds reasonable. 👍

**Review by adutra — APPROVED** [review]

File: core/src/main/java/com/datastax/oss/driver/internal/core/metrics/HdrReservoir.java [hunk 10]
```diff
@@ -0,0 +1,240 @@
...
+    throw new UnsupportedOperationException("HdrReservoir does not implement size()");
+  }
+
+  @Override
+  public Snapshot getSnapshot() {
+    long now = System.nanoTime();
+
+    cacheLock.readLock().lock();
+    try {
+      if (now < cachedHistogramTimestampNanos + refreshIntervalNanos) {
```
Comment (adutra) [inline core/src/main/java/com/datastax/oss/driver/internal/core/metrics/HdrReservoir.java]: This can overflow so I think the recommended approach is to use `(now - cachedHistogramTimestampNanos) > refreshIntervalNanos`

File: core/src/main/java/com/datastax/oss/driver/internal/core/metrics/HdrReservoir.java [hunk 11]
```diff
@@ -0,0 +1,240 @@
...
+        return cachedSnapshot;
+      }
+    } finally {
+      cacheLock.readLock().unlock();
+    }
+
+    cacheLock.writeLock().lock();
+    try {
+      // Might have raced with another writer => re-check the timestamp
+      if (now >= cachedHistogramTimestampNanos + refreshIntervalNanos) {
```
Comment (adutra) [inline core/src/main/java/com/datastax/oss/driver/internal/core/metrics/HdrReservoir.java]: Same here

File: core/src/main/resources/reference.conf [hunk 12]
```diff
@@ -553,16 +553,48 @@ datastax-java-driver {
...
+        cql_requests,
+      ]
+
+      # Extra configuration (for the metrics that need it)
+      cql_requests {
+        # The largest latency that we expect to record (should be consistent with request.timeout).
+        #
+        # This is used to scale internal data structures. If a higher recording is encountered at
+        # runtime, it is discarded and a warning is logged.
+        highest_latency = 2 seconds
```
Comment (adutra) [inline core/src/main/resources/reference.conf]: Shouldn't we default then to `${request.timeout}`?

**Review by adutra — CHANGES_REQUESTED** [review]

File: core/src/main/resources/reference.conf (hunk 12 above)
Comment (olim7t) [reply core/src/main/resources/reference.conf]: 👍 
I wonder if there is a risk of observing a higher value because of some processing overhead though. With significant_digits = 3 it would have to be a few milliseconds more, so I think we're safe. At worst it will come up as a warning and we can advise users to configure it a bit higher.

File: core/pom.xml (hunk 1 above)
Comment (olim7t) [reply core/pom.xml:84]: I double-checked and actually you're right, I stand corrected.

But there is a way to do it from outside the driver: build the `JmxReporter` with an `ObjectNameFactory` that turns every dot-separated component into a subdirectory:

```java
ObjectNameFactory objectNameFactory = (type, domain, name) -> {
  StringBuilder objectName = new StringBuilder(domain).append(':');
  List<String> nameParts = Splitter.on('.').splitToList(name);
  int i = 0;
  for (String namePart : nameParts) {
    boolean isLast = (i == nameParts.size() - 1);
    String key =
        isLast ? "name" : Strings.padStart(Integer.toString(i), 2, '0');
    objectName.append(key).append('=').append(namePart);
    if (!isLast) {
      objectName.append(',');
    }
    i += 1;
  }
  try {
    return new ObjectName(objectName.toString());
  } catch (MalformedObjectNameException e) {
    throw new RuntimeException(e);
  }
};

JmxReporter reporter =
    JmxReporter.forRegistry(session.getMetricRegistry())
        .inDomain("com.datastax.oss.driver")
        .createsObjectNamesWith(objectNameFactory)
        .build()
```

**Review by adutra — COMMENTED** [review]
Looking excellent so far 👍

File: core/src/main/java/com/datastax/oss/driver/internal/core/metrics/HdrReservoir.java [hunk 13]
```diff
@@ -0,0 +1,241 @@
...
+   * <p>This reservoir implementation is intended for use with a {@link
+   * com.codahale.metrics.Histogram}, which doesn't use this method.
+   */
+  @Override
+  public int size() {
+    throw new UnsupportedOperationException("HdrReservoir does not implement size()");
+  }
+
+  @Override
+  public Snapshot getSnapshot() {
```
Comment (tolbertam) [inline core/src/main/java/com/datastax/oss/driver/internal/core/metrics/HdrReservoir.java]: Since live and cached are only switched out on call to `getSnapshot` is there a risk that there can be more data in live and the cached is extra stale if `getSnapshot` is called on intervals > `refreshInterval`?  Since the refreshInterval is configurable I think it's fine, since we can just tell users to set it to the same duration they are using in their Reporters.

**Comment by olim7t** [comment]
I added the remaining metrics compared to what was available in 3.0.

File: core/src/main/java/com/datastax/oss/driver/internal/core/cql/CqlRequestHandlerBase.java [hunk 14]
```diff
@@ -304,6 +270,12 @@ private void setFinalResult(
           Conversions.toResultSet(resultMessage, executionInfo, session, context);
       if (result.complete(resultSet)) {
         cancelScheduledTasks();
+        session
+            .getMetricUpdater()
+            .updateTimer(
+                CoreSessionMetric.cql_requests,
+                System.nanoTime() - startTimeNanos,
```
Comment (tolbertam) [inline core/src/main/java/com/datastax/oss/driver/internal/core/cql/CqlRequestHandlerBase.java]: Is the reason `nanoTime` is used instead of `Timer.Context` because we can't be sure that a `Timer` is actually in use as metrics can be disabled?

**Review by tolbertam — COMMENTED** [review]
Looks really good so far.  Going to play with this a little bit in an environment and will report back

File: core/src/main/java/com/datastax/oss/driver/internal/core/cql/CqlRequestHandlerBase.java (hunk 14 above)
Comment (olim7t) [reply core/src/main/java/com/datastax/oss/driver/internal/core/cql/CqlRequestHandlerBase.java]: Yes, it is to avoid the extra object allocation, especially if the metric is disabled.

File: core/pom.xml (hunk 1 above)
Comment (adutra) [reply core/pom.xml:84]: Yes that's basically how we configured the JMX reporter in DSBulk. 👍

**Review by adutra — APPROVED** [review]

File: core/src/main/java/com/datastax/oss/driver/internal/core/metrics/DefaultNodeMetricUpdater.java [hunk 15]
```diff
@@ -0,0 +1,126 @@
...
+import org.slf4j.LoggerFactory;
+
+public class DefaultNodeMetricUpdater extends MetricUpdaterBase<NodeMetric>
+    implements NodeMetricUpdater {
+
+  private static final Logger LOG = LoggerFactory.getLogger(DefaultNodeMetricUpdater.class);
+
+  private final String metricNamePrefix;
+
+  public DefaultNodeMetricUpdater(
```
Comment (tolbertam) [inline core/src/main/java/com/datastax/oss/driver/internal/core/metrics/DefaultNodeMetricUpdater.java]: I noticed that a lot of metrics were not showing up, it looks like its because they aren't being registered here.  I.E. at the node level I just see `pooled_connection_count`, `available_stream_count` and `cql_messages`, but there's a lot more in `CoreNodeMetric`.

File: core/src/main/java/com/datastax/oss/driver/internal/core/metrics/DefaultSessionMetricUpdater.java [hunk 16]
```diff
@@ -0,0 +1,81 @@
...
+
+public class DefaultSessionMetricUpdater extends MetricUpdaterBase<SessionMetric>
+    implements SessionMetricUpdater {
+
+  private static final Logger LOG = LoggerFactory.getLogger(DefaultSessionMetricUpdater.class);
+
+  private final String metricNamePrefix;
+
+  public DefaultSessionMetricUpdater(
+      Set<SessionMetric> enabledMetrics, InternalDriverContext context) {
```
Comment (tolbertam) [inline core/src/main/java/com/datastax/oss/driver/internal/core/metrics/DefaultSessionMetricUpdater.java:32]: Missing registration of `cql_client_timeouts`

File: core/src/main/resources/reference.conf [hunk 17]
```diff
@@ -550,6 +566,183 @@ datastax-java-driver {
...
+        # The number of errors encountered while trying to establish a connection to this node
+        # (exposed as a Counter).
+        #
+        # Connection errors are not a fatal issue for the driver, failed connections will be retried
+        # periodically according to the reconnection policy. You can choose whether or not to log
+        # those errors at WARN level with the connection.warn-on-init-error option.
+        #
+        # Authentication errors are not included in this counter, they are tracked separately in
+        # authentication_errors.
+        // connection_errors,
```
Comment (tolbertam) [inline core/src/main/resources/reference.conf]: Should `connection_errors` and `authentication_errors` be under `errors.`?

Comment (olim7t) [reply core/src/main/resources/reference.conf]: They relate to connections while the others are more specifically for requests, so maybe I should have two sub-categories.

Comment (tolbertam) [reply core/src/main/resources/reference.conf]: good point, maybe differentiating into `connection_errors` and `request_errors` or something, and then renaming the current `connection_errors` to something like more specific like `startup_errors` or something like that.

File: core/src/main/resources/reference.conf [hunk 18]
```diff
@@ -550,6 +566,183 @@ datastax-java-driver {
...
+    }
+    # The node-level metrics (all disabled by default).
+    node {
+      enabled = [
+        # The number of connections open to this node for regular requests (exposed as a
+        # Gauge<Integer>).
+        #
+        # This does not include the control connection (which uses at most one extra connection to a
+        # random node in the cluster).
+        // pooled_connection_count,
```
Comment (tolbertam) [inline core/src/main/resources/reference.conf]: Just brainstorming (maybe i'm over thinking it).  A side effect of the granularity of being able to turn individual metrics on/off is that there are a few downsides:

1. If you want to include all metrics, you have to extract them all from this file and put them into your application.conf.  It's a bit tedious to have to copy the individual ones, but It's tolerable.

2. If a new metric is added, the user has to know about it and add it to their application.conf.

One possible solution would be to make the configuration more coarse and allow enabling metrics by category, i.e.:

```
enabled = [
  pooled_connection_count,
  available_stream_count,
  errors,
  retries,
  ignores
]
```

I wouldn't expect someone to selectively enable/disable specific retries for example, either they'd enable all of them or disable all of them.

you could also categorize `pooled_connection_count` , `available_stream_count` under a `pool` group or something.

File: core/src/main/java/com/datastax/oss/driver/api/core/metrics/CoreNodeMetric.java [hunk 19]
```diff
@@ -23,12 +23,12 @@
   POOLED_CONNECTION_COUNT("pooled_connection_count"),
   AVAILABLE_STREAM_COUNT("available_stream_count"),
   CQL_MESSAGES("cql_messages"),
-  WRITE_ERRORS("errors.write_errors"),
-  ABORTED_REQUESTS("errors.aborted_requests"),
-  WRITE_TIMEOUTS("errors.write_timeouts"),
-  READ_TIMEOUTS("errors.read_timeouts"),
-  UNAVAILABLES("errors.unavailables"),
-  OTHER_ERRORS("errors.others"),
+  UNSENT_REQUESTS("errors.request.unsent"),
```
Comment (olim7t) [inline core/src/main/java/com/datastax/oss/driver/api/core/metrics/CoreNodeMetric.java]: Renamed this because "write errors" was too similar to "write timeouts".

Comment (tolbertam) [reply core/src/main/java/com/datastax/oss/driver/api/core/metrics/CoreNodeMetric.java]: 👍 i also like what you did with the hierarchy (`errors.request` / `errors.connection`)

File: core/src/main/resources/reference.conf (hunk 18 above)
Comment (olim7t) [reply core/src/main/resources/reference.conf]: > If a new metric is added, the user has to know about it and add it to their application.conf

Yes, but on the flip side if metrics are enabled by default, then you risk introducing new (potentially expensive) metrics in existing environments, without the user's notice. I've been pondering on this "enabled vs disabled by default" question since the beginning of this PR, I think I prefer being conservative. We'll advertise new metrics in release notes and the upgrade guide.

> If you want to include all metrics, you have to extract them all from this file and put them into your application.conf. It's a bit tedious

At least that encourages you to read all the descriptions 😉

Comment (tolbertam) [reply core/src/main/resources/reference.conf]: > At least that encourages you to read all the descriptions 😉

Haha fair enough!  There isn't much of a downside in educating what the metrics **actually mean** (especially when it comes to the timer-based ones) and it will be a one time task.   I think i'm 👍  on the current configuration.

**Comment by tolbertam** [comment]
small nit:  The formatter doesn't like core/src/test/java/com/datastax/oss/driver/internal/core/pool/ChannelPoolInitTest.java

File: core/src/main/java/com/datastax/oss/driver/internal/core/metrics/DefaultNodeMetricUpdater.java [hunk 20]
```diff
@@ -44,11 +44,7 @@ public DefaultNodeMetricUpdater(
     if (enabledMetrics.contains(CoreNodeMetric.OPEN_CONNECTIONS)) {
       metricRegistry.register(
           buildFullName(CoreNodeMetric.OPEN_CONNECTIONS),
-          (Gauge<Integer>)
-              () -> {
-                ChannelPool pool = context.poolManager().getPools().get(node);
-                return (pool == null) ? 0 : pool.size();
-              });
+          (Gauge<Integer>) node::getOpenConnections);
```
Comment (olim7t) [inline core/src/main/java/com/datastax/oss/driver/internal/core/metrics/DefaultNodeMetricUpdater.java]: duh

File: core/src/main/resources/reference.conf [hunk 21]
```diff
@@ -550,6 +566,198 @@ datastax-java-driver {
     token-map.enabled = true
   }
 
+  metrics {
+    # The session-level metrics (all disabled by default).
+    session {
+      enabled = [
+        # The number of nodes to which the driver has at least one active connection (exposed as a
+        # Gauge<Integer>).
+        //connected-nodes,
```
Comment (tolbertam) [inline core/src/main/resources/reference.conf]: Very tiny nit, no space between `//` and `connected-nodes` where other metrics have a space.

**Review by tolbertam — APPROVED** [review]
This looks and is working great!  Much improved over the 3.x implementation.  👍
